---
output: html_document
---

## Session 2

Date/Time: Friday 9/8, 10 AM
Location: GRJ245

### Objectives

*	Gain an appreciation for spaced repetition as a learning strategy
*	Install Anki on your computer and import the Anki deck containing questions from the first session.

Please view the following:
1.	Spaced Repetition: https://www.youtube.com/watch?v=cVf38y07cfk
2.	Anki 2: Shared decks and review basics: https://www.youtube.com/watch?v=QS2G-k2hQyg&yt:cc=on

Please read the following:
*	Twenty Rules of Formulating Knowledge (don’t worry about the references to the different versions of SuperMemo, it’s a program similar to Anki): https://www.supermemo.com/en/articles/20rules

Please install Anki on your desktop and/or laptop and load the first session’s deck.
*	Anki 2: https://apps.ankiweb.net/
*	Optional: Set up an Ankiweb account to sync your decks between devices and review cards on the web: https://ankiweb.net/ 

Swirl modules:
1.	R Programming: Vectors
2.	R Programming: Missing Values

I recommend Anki Essentials by Alex Vermeer, a detailed and practical illustrated guide to Anki: https://foggymountainpass.com/anki-essentials/. This ebook used to be free but is now $5 to download. Here are some sample chapters: https://alexvermeer.com/wp-content/uploads/Anki-Essentials-Free-Chapters.pdf
