---
output: html_document
---

<!-- 

TO DO:
- Review Ankis and create .html, .pdf, .apkg
- Upload and link code book

TO THE INSTRUCTOR:
- Go over the few dplyr cards
- Have everyone download and load the Rmd document, answer the questions, and fill in the prompts

-->

## Session 4: Manipulating Data Frames with dplyr

| Date    | Time      | Location |
|---------|-----------|----------|
| 9/15/17 | 10 AM     | GRJ245   |

### Objectives

*	Become familiar with the following aspects of R:
    * The pipe `%>%` operator
    * The dplyr functions `select()`, `filter()`, `arrange()`, and `mutate()`
    * The split-apply-combine workflow with `group_by()` and `summarize()`
    * Augmenting a data frame with data stored in another data frame using `left_join()`

### Pre-Session Activities

Please view the following:

* **[4 min]** [The Pipe Operator](https://www.youtube.com/watch?v=9yjhxvu-pDg) (Ben Stenhaug, Stanford)
* **[10 min]** [The 5 Verbs of dplyr](https://www.youtube.com/watch?v=sVISY_27znA) (Ben Stenhaug, Stanford)
* **[3 min]** [Understanding Joins](https://www.youtube.com/watch?v=Eqvm9KYWEO4) (Garrett Grolemund, RStudio, DataCamp)

Please install the **Getting and Cleaning Data** swirl course by issuing the following commands in R:
```{r, eval=FALSE}
library(swirl)
install_course("Getting and Cleaning Data")
```

Swirl modules:

* Getting and Cleaning Data: Manipulating Data with dplyr[^1]
* Getting and Cleaning Data: Grouping and Chaining with dplyr

### Materials

* [Framingham data set (Excel)](framingham.xlsx)
* <a href="framingham_no_answers.Rmd" download="framingham_no_answers.Rmd">Framingham Case Study (Rmd, no answers)</a> <!-- Force download to prevent showing Rmd in browser -->
* [Framingham Case Study Code Book (PDF)](framingham_code_book.pdf)
* [Session 4 slides (Slidy)](04_ankis.html)
* [Session 4 hand-out (no answers)](04_ankis_no_answers.pdf)
* [Session 4 Anki cards (.apkg)](04_ankis.apkg)